### ISSUE TITLE
Proprietary dependency: GMS

### ISSUE THREAD

**Issue by IzzySoft** [printpagestopdf/cb_app#1]
I've just performed a scan on your APK as you've opened an inclusion request with F-Droid. Looks there's a little show-stopper here. This is what the scanner results look like:

```
Libraries detected:
-------------------
* Android PackageManager (/android/content/pm): Utility, Apache-2.0
* Android Support v4 (/android/support/v4): Development Framework, Apache-2.0
* AndroidX Activity (/androidx/activity): Utility, Apache-2.0
* Android Jetpack Annotations (/androidx/annotation): Utility, Apache-2.0
* Browser (/androidx/browser): Utility, Apache-2.0
* Androidx Core (/androidx/core): Utility, Apache-2.0
* AndroidX Fragment (/androidx/fragment): UI Component, Apache-2.0
* Lifecycle (/androidx/lifecycle): Utility, Apache-2.0
* Loader (/androidx/loader): Utility, Apache-2.0
* Android Activity Saved State (/androidx/savedstate): Utility, Apache-2.0
* AndroidX Security (/androidx/security): Utility, Apache-2.0
* Android Jetpack VersionedParcelable (/androidx/versionedparcelable): Utility, Apache-2.0
* Jetpack WindowManager Library (/androidx/window): Utility, Apache-2.0
* Flutter Geolocator Plugin (/com/baseflow/geolocator): Utility, MIT
* Google Mobile Services (/com/google/android/gms): Development Framework, Proprietary; NonFreeComp
* Tink (/com/google/crypto/tink): Utility, Apache-2.0
* Flutter (/io/flutter): Development Framework, BSD-3-Clause
* url_launcher (/io/flutter/plugins/urllauncher): Utility, BSD-3-Clause
* Kotlin (/kotlin): Utility, Apache-2.0
* kotlinx.coroutines (/kotlinx/coroutines): Utility, Apache-2.0

Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeComp

1 offenders.

Dangerous flags:
----------------
* usesCleartextTraffic

Permissions:
------------
* android.permission.INTERNET
* android.permission.ACCESS_NETWORK_STATE
* android.permission.ACCESS_FINE_LOCATION
* android.permission.ACCESS_COARSE_LOCATION
* com.theripper.cb_app.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

See the GMS (Google Mobile Services)? Those are a show-stopper for F-Droid. The most likely culprit having dragged that in: Flutter Geolocator Plugin. Some pointers for help can be found in the corresponding section of my snippet under [Flutter and Geolocation](https://gitlab.com/-/snippets/1896503#flutter-and-geolocation).

Further, I see your app declares `usesCleartextTraffic`. Does it really rely on any unencrypted network connections (i.e. `http://` instead of `https://`)? If not, you may want to remove that flag from your declaration in `AndroidManifest.xml`.

Oh, and if you wonder about that `DEPENDENCY_INFO_BLOCK`, that can be avoided with a small modification to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by printpagestopdf** [comment]
Thank you for this quick response.

Wasn't aware about this Problem with Geolocation on Android, but that's understandable. I will investigate possibilities to get rid of this (e.g. following your link/suggestion).

Regarding usesCleartextTraffic: Users of the App decide which site they are connecting that is using the  [CommonsBooking ](https://github.com/wielebenwir/commonsbooking) Plugin. Such sites are normaly driven by non-profit associations that perhaps have good IT ressources or not. So I can't know in advance if there are sites outside that are still using http only. It is up to the users of such sites (and the App) if they want to take this risk or not.

**Comment by IzzySoft** [comment]
Thanks for the details! Looking forward to your resolution of the Geolocation issue then.

As for cleartext: Yes, that's understandable then. Maybe you have already something like this in place, but let me mention it nevertheless: Say I am using your app and enter such a `http://` URL. That could even be accidentally and I just forgot the `s` (or my keyboard ate it). Would there be a "warning" of some kind telling me: "hey, that's not a secured URL. You sure you want to use that without https?" – giving me a chance to fix my mistake, or to say "yes, I know what I'm doing"? Once confirmed it is saved to the settings anyway, so no future warnings on using that site. What do you think?

**Comment by printpagestopdf** [comment]
Geolocation problem is solved for the FLOSS build for F-Droid.

Regarding the other question: There is already a more detailed check of the service url, that gives the user a report of the connection test (url connectable, REST API available, CommonsAPI available ....) on a new added url. 
Thats not exactly what you mentioned, and I see your point.  So I would add this warning to the next version.

**Comment by IzzySoft** [comment]
Thanks a lot!

**Comment by printpagestopdf** [comment]
Added warning Dialog if using http
